language: go

sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9

before_install:
  - go get -u github.com/signalfx/gobuild
  - go get -u github.com/alecthomas/gometalinter 
  - gometalinter --install --update

install:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host git.apache.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - go get -d -v -t ./...
  - CUR=$PWD
  - cd "$GOPATH/src/git.apache.org/thrift.git/"
  - git checkout 53dd39833a08ce33582e5ff31fa18bb4735d6731
  - cd "$CUR"

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOCOVERDIR_DIR="."
  - env GOCONVEY_REPORTER=silent GOLIB_LOG=/dev/null gobuild

after_script:
  - cat coverage.out

